# Generated by Django 5.0.6 on 2024-07-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
