# Generated by Django 5.0.6 on 2024-07-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
